services:

  # Oxxxxxxx[======= Gateway ==================================================>
  gateway:
    container_name: camagru-gateway
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/nginx/certs:/etc/nginx/certs:ro
      - ./app/frontend/public:/var/www/frontend/public:ro
    depends_on:
      - auth
      - media
      - post
      - notification
    networks:
      - camagru

  # Oxxxxxxx[======= Auth Service =============================================>
  auth:
    container_name: camagru-auth
    build:
      context: ./app/services/auth
      dockerfile: Dockerfile
    volumes:
      - ./app/services/auth:/var/www/html
      - auth-data:/var/www/html/data
    env_file: ./secrets/.env
    environment:
      - SERVICE_NAME=auth
    networks:
      - camagru

  # Oxxxxxxx[======= Media Service ============================================>
  media:
    container_name: camagru-media
    build:
      context: ./app/services/media
      dockerfile: Dockerfile
    volumes:
      - ./app/services/media:/var/www/html
      - media-data:/var/www/html/data
      - media-uploads:/var/www/html/uploads
    env_file: ./secrets/.env
    environment:
      - SERVICE_NAME=media
    networks:
      - camagru

  # Oxxxxxxx[======= Post Service =============================================>
  post:
    container_name: camagru-post
    build:
      context: ./app/services/post
      dockerfile: Dockerfile
    volumes:
      - ./app/services/post:/var/www/html
      - post-data:/var/www/html/data
    env_file: ./secrets/.env
    environment:
      - SERVICE_NAME=post
    networks:
      - camagru

  # Oxxxxxxx[======= Notification Service =====================================>
  notification:
    container_name: camagru-notification
    build:
      context: ./app/services/notification
      dockerfile: Dockerfile
    volumes:
      - ./app/services/notification:/var/www/html
      - notif-data:/var/www/html/data
    env_file: ./secrets/.env
    environment:
      - SERVICE_NAME=notification
    networks:
      - camagru

  # Oxxxxxxx[======= Mail Catcher =============================================>
  mailhog:
    container_name: camagru-mailhog
    image: docker.io/mailhog/mailhog:latest
    platform: linux/amd64
    ports:
      - "8025:8025"
    networks:
      - camagru

# Oxxxxxxx[======= Volumes (1 micro db par service) ===========================>
volumes:
  auth-data:
  media-data:
  media-uploads:
  post-data:
  notif-data:

# Oxxxxxxx[======= Network interne ============================================>
networks:
  camagru:
    driver: bridge
