services:
  web:
    build: ./docker/web
    container_name: camagru-web
    ports:
      - "8080:80"
    volumes:
      - ./camagru/public:/var/www/html/public
      - ./camagru/app:/var/www/html/app
      - ./camagru/config:/var/www/html/config
      - ./camagru/database:/var/www/html/database
    env_file: .env
    depends_on:
      - db
      - mailhog

  db:
    image: docker.io/library/postgres:16-alpine
    container_name: camagru-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./camagru/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5432:5432"

  mailhog:
    image: docker.io/mailhog/mailhog:latest
    container_name: camagru-mailhog
    ports:
      - "1025:1025"   # SMTP app
      - "8025:8025"   # Interface web : http://localhost:8025

volumes:
  db-data:
