services:
  web:
    volumes:
      - ./camagru/public:/var/www/html/public
      - ./camagru/app:/var/www/html/app
      - ./camagru/config:/var/www/html/config

  db:
    ports:
      - "5432:5432"
